# Generated by Django 5.1.8 on 2026-06-24 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracer', '0085_alter_errorclustertraces_trace_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracescanconfig',
            name='last_swept_at',
            field=models.DateTimeField(blank=True, help_text="High-water mark for the periodic scan sweep: the ClickHouse ingest time (root span created_at) up to which this project's completed traces have been considered for scanning. The sweep scans (last_swept_at, now-grace] and advances this. NULL = never swept (cold start scans a bounded recent window).", null=True),
        ),
    ]
